import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Use Effect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.useEffect}>
          <h1>Type of Use Effects</h1>
          <div className={styles.useEffectTypes}>
            <Link className={styles.useEffectLinks} href="/useEffectOne">useEffectOne</Link>
            <Link className={styles.useEffectLinks} href="/useEffectTwo">useEffectTwo</Link>
            <Link className={styles.useEffectLinks} href="/useEffectThree">useEffectThree</Link>          
          </div>
        </div>
        <div className={styles.next}>
          <h3>Carousel Images - </h3>
          <Link className={styles.carouselPage} href="/carouselPage">Click here!</Link>
        </div>
        
      </main>
    </>
  )
}
